/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pverbovshchuk' at '9/20/16 6:26 PM' with Gradle 2.14.1
 *
 * @author pverbovshchuk, @date 9/20/16 6:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
